const blackcards = [
  { name: "Absurd", subtitle: "(ridiculous, senseless, foolish)" },
{ name: "Abundant", subtitle: "(plentiful, ample, numerous)" },
{ name: "Addictive", subtitle: "(obsessive, consuming, captivating)" },
{ name: "Adorable", subtitle: "(lovable, charming, delightful)" },
{ name: "Adorable", subtitle: "(lovable, cute)" },
{ name: "Aged", subtitle: "(old, ancient, mature)" },
{ name: "Amazing", subtitle: "(astonishing, surprising, wonderful)" },
{ name: "Amazing", subtitle: "(surprising, wonderful)" },
{ name: "American", subtitle: "(U.S. Citizen, Yankee, Apple Pie)" },
{ name: "Ancient", subtitle: "(elderly, old, antique)" },
{ name: "Animated", subtitle: "(lively, exuberant, spirited)" },
{ name: "Annoying", subtitle: "(irritating, bothersome, teasing)" },
{ name: "Annoying", subtitle: "(bothersome, irritating)" },
{ name: "Appetizing", subtitle: "(appealing, tasty, flavorful)" },
{ name: "Armed & Dangerous", subtitle: "(hazardous, threatening, fortified)" },
{ name: "Arrogant", subtitle: "(egotistical, overconfident, conceited)" },
{ name: "Attractive", subtitle: "(alluring, engaging, good-looking)" },
{ name: "Attractive", subtitle: "(pretty, good-looking)" },
{ name: "Awesome", subtitle: "(amazing, remarkable, majestic)" },
{ name: "Awful", subtitle: "(very bad, horrible)" },
{ name: "Awkward", subtitle: "(clumsy, bumbling, uncoordinated)" },
{ name: "Bad", subtitle: "(rotten, hurtful)" },
{ name: "Bashful", subtitle: "(shy, timid, modest)" },
{ name: "Beautiful", subtitle: "(pretty, lovely)" },
{ name: "Believable", subtitle: "(trustworthy, credible, convincing)" },
{ name: "Best", subtitle: "(greatest, finest)" },
{ name: "Big", subtitle: "(large, huge)" },
{ name: "Big & Tall", subtitle: "(large, bulky, gigantic)" },
{ name: "Bitter", subtitle: "(sour, tart)" },
{ name: "Black & Blue", subtitle: "(bruised, battered, rough)" },
{ name: "Black & White", subtitle: "(indisputable, distinct, written)" },
{ name: "Bogus", subtitle: "(fraudulent, phony, insincere)" },
{ name: "Boisterous", subtitle: "(loud, rambunctious, rowdy)" },
{ name: "Bold", subtitle: "(daring, brave, courageous)" },
{ name: "Bold", subtitle: "(daring, courageous)" },
{ name: "Boring", subtitle: "(dull, tedious, monotonous)" },
{ name: "Boring", subtitle: "(not interesting, dull)" },
{ name: "Brains & Brawn", subtitle: "(solid, strong, capable)" },
{ name: "Brave", subtitle: "(fearless, courageous)" },
{ name: "Bright", subtitle: "(brilliant, radiant, shiny)" },
{ name: "Bright", subtitle: "(light, intelligent)" },
{ name: "Bright & Shining", subtitle: "(radiant, sparkling, gleaming)" },
{ name: "Brilliant", subtitle: "(dazzling, gleaming, intelligent)" },
{ name: "Brutal", subtitle: "(cruel, crude, harsh)" },
{ name: "Bumpy", subtitle: "(lumpy, bouncy)" },
{ name: "Busy", subtitle: "(occupied, meddlesome, engrossed)" },
{ name: "Busy", subtitle: "(active, unavailable)" },
{ name: "Calm", subtitle: "(peaceful, tranquil, placid)" },
{ name: "Calm", subtitle: "(peaceful, still)" },
{ name: "Careful", subtitle: "(cautious, thoughtful)" },
{ name: "Caring", subtitle: "(concerned, interested)" },
{ name: "Casual", subtitle: "(easygoing, blase, nonchalant)" },
{ name: "Charismatic", subtitle: "(alluring, magnetic, charming)" },
{ name: "Charming", subtitle: "(captivating, enchanting, fascinating)" },
{ name: "Charming", subtitle: "(pleasant, polite)" },
{ name: "Cheerful", subtitle: "(happy, lively)" },
{ name: "Cheesy", subtitle: "(trashy, tawdry, far-fetched)" },
{ name: "Chewy", subtitle: "(gummy, rubbery, stringy)" },
{ name: "Chewy", subtitle: "(gummy, rubbery)" },
{ name: "Chubby", subtitle: "(plump, round)" },
{ name: "Chunky", subtitle: "(lumpy, chubby, bumpy)" },
{ name: "Classic", subtitle: "(timeless, definitive, vintage)" },
{ name: "Clean", subtitle: "(washed, pure, tidy)" },
{ name: "Clean", subtitle: "(spotless, clear)" },
{ name: "Clear", subtitle: "(understandable, uncluttered, transparent)" },
{ name: "Clever", subtitle: "(intelligent, ingenious, witty)" },
{ name: "Clueless", subtitle: "(unaware, oblivious, ignorant)" },
{ name: "Clumsy", subtitle: "(awkward, bumbling, uncoordinated)" },
{ name: "Clumsy", subtitle: "(awkward, not graceful)" },
{ name: "Cold", subtitle: "(chilly, icy, aloof)" },
{ name: "Cold", subtitle: "(cool, chilly)" },
{ name: "Colorful", subtitle: "(vivid, brilliant, kaleidoscopic)" },
{ name: "Colorful", subtitle: "(full of color, bright)" },
{ name: "Comfortable", subtitle: "(cozy, snug, restful)" },
{ name: "Comfortable", subtitle: "(cozy, pleasant)" },
{ name: "Comical", subtitle: "(funny, hilarious, amusing)" },
{ name: "Complicated", subtitle: "(difficult, complex, involved)" },
{ name: "Conceited", subtitle: "(vain, smug, self-centered)" },
{ name: "Confused", subtitle: "(muddled, bewildered, perplexed)" },
{ name: "Confusing", subtitle: "(puzzling, weird)" },
{ name: "Controversial", subtitle: "(contentious, disputable, debatable)" },
{ name: "Cool", subtitle: "(chilly, hip, cold-blooded)" },
{ name: "Cool", subtitle: "(not hot, chilled)" },
{ name: "Cool & Collected", subtitle: "(controlled, composed, restrained)" },
{ name: "Corrupt", subtitle: "(dishonest, underhanded, shady)" },
{ name: "Cosmic", subtitle: "(limitless, planetary, far out)" },
{ name: "Cosmopolitan", subtitle: "(sophisticated, urbane, well-informed)" },
{ name: "Costly", subtitle: "(expensive, valuable)" },
{ name: "Courageous", subtitle: "(brave, gallant, dauntless)" },
{ name: "Courageous", subtitle: "(brave, bold)" },
{ name: "Cowardly", subtitle: "(fearful, afraid, spineless)" },
{ name: "Cozy", subtitle: "(comfortable, snug, warm)" },
{ name: "Cozy", subtitle: "(comfortable, warm)" },
{ name: "Cranky", subtitle: "(crabby, cantankerous, grouchy)" },
{ name: "Crazed", subtitle: "(insane, wild, deranged)" },
{ name: "Crazy", subtitle: "(insane, bizarre, wacky)" },
{ name: "Crazy", subtitle: "(silly, foolish)" },
{ name: "Creative", subtitle: "(imaginative, artistic, original)" },
{ name: "Creepy", subtitle: "(frightening, slithering, scary)" },
{ name: "Creepy", subtitle: "(spooky, scary)" },
{ name: "Creepy & Crawly", subtitle: "(frightening, ghastly, icky)" },
{ name: "Crisp", subtitle: "(brittle, brisk, fresh)" },
{ name: "Crisp & Delicious", subtitle: "(tasty, crunchy, savory)" },
{ name: "Crooked", subtitle: "(bent, not straight)" },
{ name: "Cruel", subtitle: "(mean, harsh, merciless)" },
{ name: "Cruel & Unusual", subtitle: "(barbaric, merciless, unwarranted)" },
{ name: "Crunchy", subtitle: "(crispy, crackling)" },
{ name: "Cuddly", subtitle: "(loving, tender, huggable)" },
{ name: "Cuddly", subtitle: "(cozy, soft)" },
{ name: "Curved", subtitle: "(bent, rounded)" },
{ name: "Cut & Dried", subtitle: "(settled, obvious, indisputable)" },
{ name: "Cute", subtitle: "(pretty, perky, delightful)" },
{ name: "Cute", subtitle: "(pretty, good-looking)" },
{ name: "Cute & Cuddly", subtitle: "(adorable, precious, huggable)" },
{ name: "Dainty", subtitle: "(delicate, fragile, thin)" },
{ name: "Dainty", subtitle: "(delicate, elegant)" },
{ name: "Dangerous", subtitle: "(risky, chancy, hazardous)" },
{ name: "Dangerous", subtitle: "(unsafe, risky)" },
{ name: "Daring", subtitle: "(brave, bold)" },
{ name: "Dark", subtitle: "(unlit, morbid, sinister)" },
{ name: "Dark", subtitle: "(without light, nearly black)" },
{ name: "Dashing", subtitle: "(gallant, bold, elegant)" },
{ name: "Dazed & Confused", subtitle: "(stunned, bewildered, disoriented)" },
{ name: "Dead", subtitle: "(deceased, expired, unresponsive)" },
{ name: "Dead & Gone", subtitle: "(deceased, defunct, passe)" },
{ name: "Deadly", subtitle: "(fatal, lethal, murderous)" },
{ name: "Delicate", subtitle: "(dainty, tender, elegant)" },
{ name: "Delicate", subtitle: "(breakable, dainty)" },
{ name: "Delicious", subtitle: "(tasty, pleasing, appetizing)" },
{ name: "Delicious", subtitle: "(tasty, pleasing)" },
{ name: "Delightful", subtitle: "(pleasing, enjoyable, charming)" },
{ name: "Demanding", subtitle: "(difficult, exacting, bothersome)" },
{ name: "Depressing", subtitle: "(dismal, gloomy, sad)" },
{ name: "Desperate", subtitle: "(frantic, headlong, reckless)" },
{ name: "Devious", subtitle: "(sneaky, shifty, tricky)" },
{ name: "Difficult", subtitle: "(complicated, hard)" },
{ name: "Dignified", subtitle: "(stately, honorable, distinguished)" },
{ name: "Dirty", subtitle: "(unclean, soiled, impure)" },
{ name: "Dirty", subtitle: "(unclean, filthy)" },
{ name: "Disgusting", subtitle: "(sickening, horrible)" },
{ name: "Distinguished", subtitle: "(dignified, extraordinary, acclaimed)" },
{ name: "Disturbing", subtitle: "(unsettling, troubling, worrisome)" },
{ name: "Down & Dirty", subtitle: "(nasty, vicious, unscrupulous)" },
{ name: "Down & Out", subtitle: "(destitute, impoverished, penniless)" },
{ name: "Dramatic", subtitle: "(exciting, sensational, theatrical)" },
{ name: "Dreamy", subtitle: "(fanciful, whimsical, heavenly)" },
{ name: "Drunk & Disorderly", subtitle: "(intoxicated, unruly, rowdy)" },
{ name: "Dull", subtitle: "(boring, stupid, blunt)" },
{ name: "Dull", subtitle: "(not sharp, plain)" },
{ name: "Dumb", subtitle: "(silent, not smart)" },
{ name: "Dumb & Dumber", subtitle: "(stupid, dull, rediculous)" },
{ name: "Dysfunctional", subtitle: "(impaired, damaged, maladjusted)" },
{ name: "Earthy", subtitle: "(unrefined, natural, crude)" },
{ name: "Easy", subtitle: "(effortless, gentle, promiscuous)" },
{ name: "Easy", subtitle: "(simple, not hard)" },
{ name: "Eccentric", subtitle: "(peculiar, odd, bizarre)" },
{ name: "Edgy", subtitle: "(irritable, nervous, tense)" },
{ name: "Elderly", subtitle: "(old, aged)" },
{ name: "Elitist", subtitle: "(snobbish, arrogant, smug)" },
{ name: "Emotional", subtitle: "(passionate, moving, volatile)" },
{ name: "Enchanting", subtitle: "(captivating, charming, spell-binding)" },
{ name: "Endangered", subtitle: "(at risk, threatened, unprotected)" },
{ name: "Energetic", subtitle: "(active, vigorous, forceful)" },
{ name: "Energetic", subtitle: "(active, lively)" },
{ name: "Enjoyable", subtitle: "(pleasurable, entertaining, fun)" },
{ name: "Enjoyable", subtitle: "(pleasant, fun)" },
{ name: "Enormous", subtitle: "(large, huge, gigantic)" },
{ name: "Enormous", subtitle: "(huge, gigantic)" },
{ name: "Entertaining", subtitle: "(amusing, festive, enjoyable)" },
{ name: "Entertaining", subtitle: "(interesting, fun)" },
{ name: "Eternal", subtitle: "(timeless, immortal, perpetual)" },
{ name: "European", subtitle: "(of Europe, from Europe, about Europe)" },
{ name: "Evil", subtitle: "(wicked, corrupt, depraved)" },
{ name: "Excellent", subtitle: "(very good, outstanding)" },
{ name: "Exciting", subtitle: "(thrilling, breathtaking, arousing)" },
{ name: "Exciting", subtitle: "(thrilling, interesting)" },
{ name: "Exhausting", subtitle: "(weakening, tiring, draining)" },
{ name: "Expensive", subtitle: "(costly, valuable, exorbitant)" },
{ name: "Expensive", subtitle: "(costly, high priced)" },
{ name: "Explosive", subtitle: "(bursting, blasting, dangerous)" },
{ name: "Exquisite", subtitle: "(excellent, refined, flawless)" },
{ name: "Extreme", subtitle: "(exceptional, superlative, radical)" },
{ name: "Fabulous", subtitle: "(marvelous, wonderful, incredible)" },
{ name: "Fake", subtitle: "(unreal, counterfeit, deceptive)" },
{ name: "Famous", subtitle: "(well-known, celebrated, distinguished)" },
{ name: "Famous", subtitle: "(well-known, important)" },
{ name: "Fancy", subtitle: "(showy, ornate, decorated)" },
{ name: "Fancy", subtitle: "(decorated, elegant)" },
{ name: "Fantastic", subtitle: "(awesome, outrageous, imaginary)" },
{ name: "Fascinating", subtitle: "(interesting, attractive)" },
{ name: "Fashionable", subtitle: "(stylish, dashing, current)" },
{ name: "Fast", subtitle: "(swift, quick, rapid)" },
{ name: "Fast", subtitle: "(speedy, quick)" },
{ name: "Fast & Furious", subtitle: "(wild, reckless, breakneck)" },
{ name: "Fast & Loose", subtitle: "(deceitful, fraudulent, reckless)" },
{ name: "Fat", subtitle: "(plump, thick)" },
{ name: "Fat & Happy", subtitle: "(content, satisfied, assured)" },
{ name: "Favorite", subtitle: "(preferred, desired)" },
{ name: "Fearful", subtitle: "(scared, worried)" },
{ name: "Feminine", subtitle: "(womanly, ladylike, unmanly)" },
{ name: "Filthy", subtitle: "(dirty, foul, unclean)" },
{ name: "Fine", subtitle: "(worthy, delicate, all right)" },
{ name: "Flaky", subtitle: "(foolish, eccentric, crispy)" },
{ name: "Flamboyant", subtitle: "(ornate, pompous, extravagant)" },
{ name: "Flat", subtitle: "(smooth, level)" },
{ name: "Flavorful", subtitle: "(tasty, savory, pungent)" },
{ name: "Flavorful", subtitle: "(tasty, appetizing)" },
{ name: "Flawed", subtitle: "(imperfect, defective, unsound)" },
{ name: "Flirtatious", subtitle: "(brazen, saucy, forward)" },
{ name: "Foot Loose & Fancy Free", subtitle: "(lighthearted, carefree, spontaneous)" },
{ name: "Foreign", subtitle: "(alien, unfamiliar, exotic)" },
{ name: "Fragile", subtitle: "(delicate, frail, breakable)" },
{ name: "Fragile", subtitle: "(delicate, weak)" },
{ name: "Fragrant", subtitle: "(aromatic, odorous, perfumed)" },
{ name: "Frail", subtitle: "(fragile, weak)" },
{ name: "Frazzled", subtitle: "(exhausted, frayed, worn)" },
{ name: "Fresh", subtitle: "(new, original, good)" },
{ name: "Fresh", subtitle: "(new, clean)" },
{ name: "Friendly", subtitle: "(affectionate, comforting, welcoming)" },
{ name: "Friendly", subtitle: "(kind, nice)" },
{ name: "Frightening", subtitle: "(scary, horrifying, awesome)" },
{ name: "Frightening", subtitle: "(scary, horrifying)" },
{ name: "Frivolous", subtitle: "(trivial, silly, shallow)" },
{ name: "Funky", subtitle: "(groovy, psychedelic, hip)" },
{ name: "Fun", subtitle: "(enjoyable, playful, amusing)" },
{ name: "Fun", subtitle: "(enjoyable, playful)" },
{ name: "Funny", subtitle: "(amusing, comic, odd)" },
{ name: "Funny", subtitle: "(silly, goofy)" },
{ name: "Furious", subtitle: "(angry, raging, wild)" },
{ name: "Furry", subtitle: "(hairy, fuzzy)" },
{ name: "Fuzzy", subtitle: "(downy, unclear, furry)" },
{ name: "Fuzzy", subtitle: "(furry, fuzz-covered)" },
{ name: "Gentle", subtitle: "(tame, mild)" },
{ name: "Gigantic", subtitle: "(huge, large)" },
{ name: "Glamorous", subtitle: "(beautiful, dazzling, stylish)" },
{ name: "Glitzy", subtitle: "(flashy, showy, gaudy)" },
{ name: "Global", subtitle: "(world-wide, spherical, universal)" },
{ name: "Gloomy", subtitle: "(dreary, depressing, sullen)" },
{ name: "Glorious", subtitle: "(magnificent, delightful, splendid)" },
{ name: "Good", subtitle: "(not bad, fine)" },
{ name: "Goody-Goody", subtitle: "(sweet, well-behaved, virtuous)" },
{ name: "Goofy", subtitle: "(silly, foolish, giddy)" },
{ name: "Goofy", subtitle: "(silly, weird)" },
{ name: "Gorgeous", subtitle: "(beautiful, stunning, magnificent)" },
{ name: "Gorgeous", subtitle: "(beautiful, dazzling)" },
{ name: "Graceful", subtitle: "(elegant, supple, limber)" },
{ name: "Graceful", subtitle: "(elegant, flowing)" },
{ name: "Great", subtitle: "(very good, important)" },
{ name: "Grueling", subtitle: "(demanding, exhausting, strenuous)" },
{ name: "Gruesome", subtitle: "(ghastly, hideous, grisly)" },
{ name: "Grungy", subtitle: "(dirty, shabby, seedy)" },
{ name: "Hairy", subtitle: "(not bald, furry)" },
{ name: "Hale & Hearty", subtitle: "(healthy, vigorous, robust)" },
{ name: "Handsome", subtitle: "(attractive, elegant, fine)" },
{ name: "Handy", subtitle: "(convenient, available, capable)" },
{ name: "Handy", subtitle: "(useful, helpful)" },
{ name: "Happy", subtitle: "(glad, jolly)" },
{ name: "Hard", subtitle: "(not soft, difficult)" },
{ name: "Hardworking", subtitle: "(industrious, diligent, busy)" },
{ name: "Hardworking", subtitle: "(industrious, careful)" },
{ name: "Harmful", subtitle: "(hurtful, unhealthy, damaging)" },
{ name: "Harmful", subtitle: "(hurtful, damaging)" },
{ name: "Harsh", subtitle: "(severe, glaring, brutal)" },
{ name: "Haunting", subtitle: "(unforgettable, bewitching, unearthly)" },
{ name: "Hazardous", subtitle: "(risky, dangerous, perilous)" },
{ name: "Healthy", subtitle: "(hearty, robust, wholesome)" },
{ name: "Healthy", subtitle: "(not sick, well)" },
{ name: "Heartless", subtitle: "(insensitive, cruel, uncaring)" },
{ name: "Heavy", subtitle: "(not light, bulky)" },
{ name: "Helpful", subtitle: "(useful, assisting)" },
{ name: "High & Dry", subtitle: "(abandoned, alone, helpless)" },
{ name: "High & Low", subtitle: "(everywhere, universally, all over)" },
{ name: "High & Mighty", subtitle: "(arrogant, conceited, vain)" },
{ name: "Hilarious", subtitle: "(funny, witty, amusing)" },
{ name: "Hit & Miss", subtitle: "(sporadic, unreliable, erratic)" },
{ name: "Honest", subtitle: "(trustworthy, truthful)" },
{ name: "Honorable", subtitle: "(honest, just, virtuous)" },
{ name: "Hopeless", subtitle: "(pessimistic, desperate, downhearted)" },
{ name: "Horrible", subtitle: "(frightening, awful)" },
{ name: "Horrifying", subtitle: "(offensive, abominable, disgusting)" },
{ name: "Hostile", subtitle: "(antagonistic, aggressive, warlike)" },
{ name: "Hot", subtitle: "(blazing, heated, spicy)" },
{ name: "Hot", subtitle: "(very warm, heated)" },
{ name: "Hot & Bothered", subtitle: "(annoyed, irritated, provoked)" },
{ name: "Hot & Cold", subtitle: "(ambivalent, indecisive, varying)" },
{ name: "Hot & Heavy", subtitle: "(passionate, momentous, serious)" },
{ name: "Hot & Muggy", subtitle: "(sultry, humid, oppressive)" },
{ name: "Hot & Spicy", subtitle: "(zesty, stimulating, pungent)" },
{ name: "Hot & Sweaty", subtitle: "(sweltering, intense, perspiring)" },
{ name: "Huge", subtitle: "(gigantic, immense, important)" },
{ name: "Huge", subtitle: "(big, large)" },
{ name: "Humorous", subtitle: "(funny, amusing, comical)" },
{ name: "Icky", subtitle: "(sickening, disgusting, repulsive)" },
{ name: "Ideal", subtitle: "(perfect, flawless, model)" },
{ name: "Idiotic", subtitle: "(foolish, dumb, moronic)" },
{ name: "Important", subtitle: "(significant, substantial, momentous)" },
{ name: "Important", subtitle: "(valuable, worthwhile)" },
{ name: "Industrious", subtitle: "(diligent, busy, hard-working)" },
{ name: "Influential", subtitle: "(powerful, prominent, important)" },
{ name: "Innocent", subtitle: "(guiltless, pure, naive)" },
{ name: "Insane", subtitle: "(psychotic, deranged, mad)" },
{ name: "Inspirational", subtitle: "(exhilarating, inspiring, stimulating)" },
{ name: "Insulting", subtitle: "(offending, discourteous, rude)" },
{ name: "Intelligent", subtitle: "(bright, smart, brainy)" },
{ name: "Intense", subtitle: "(extreme, passionate, strained)" },
{ name: "Interesting", subtitle: "(fascinating, exciting)" },
{ name: "Irresistible", subtitle: "(overpowering, overwhelming, compelling)" },
{ name: "Irritating", subtitle: "(annoying, troublesome, provoking)" },
{ name: "Jolly", subtitle: "(cheerful, joyous, merry)" },
{ name: "Jolly", subtitle: "(cheerful, fun)" },
{ name: "Juicy", subtitle: "(drippy, luscious, tantalizing)" },
{ name: "Juicy", subtitle: "(wet, squishy)" },
{ name: "Kind", subtitle: "(nice, helpful)" },
{ name: "Large", subtitle: "(big, not small)" },
{ name: "Lazy", subtitle: "(lifeless, apathetic, weary)" },
{ name: "Lazy", subtitle: "(slow, careless)" },
{ name: "Lean & Mean", subtitle: "(vigorous, fit, efficient)" },
{ name: "Legendary", subtitle: "(famous, distinctive, prominent)" },
{ name: "Lewd & Lascivious", subtitle: "(lustful, obscene, indecent)" },
{ name: "Light", subtitle: "(not dark, not heavy)" },
{ name: "Light & Fluffy", subtitle: "(billowy, airy, soft)" },
{ name: "Little", subtitle: "(small, tiny)" },
{ name: "Lively", subtitle: "(cheerful, active)" },
{ name: "Long", subtitle: "(not short, stretched)" },
{ name: "Long & Lean", subtitle: "(slender, lanky, wiry)" },
{ name: "Loud", subtitle: "(noisy, boisterous, deafening)" },
{ name: "Loud", subtitle: "(noisy, not quiet)" },
{ name: "Loud & Clear", subtitle: "(definite, explicit, unequivocal)" },
{ name: "Lovable", subtitle: "(adorable, endearing, cuddly)" },
{ name: "Lovable", subtitle: "(adorable, enchanting)" },
{ name: "Loving", subtitle: "(caring, kind)" },
{ name: "Lucky", subtitle: "(fortunate, serendipitous, favored)" },
{ name: "Lucky", subtitle: "(fortunate, favored)" },
{ name: "Lumpy", subtitle: "(bumpy, clumpy)" },
{ name: "Luscious", subtitle: "(delicious, savory, juicy)" },
{ name: "Luxurious", subtitle: "(opulent, lavish, sumptuous)" },
{ name: "Magical", subtitle: "(enchanting, miraculous, marvelous)" },
{ name: "Magical", subtitle: "(mysterious, delightful)" },
{ name: "Manly", subtitle: "(masculine, virile, strong)" },
{ name: "Masculine", subtitle: "(male, manly, virile)" },
{ name: "Mean", subtitle: "(malicious, ill-tempered, petty)" },
{ name: "Mean", subtitle: "(unkind, nasty)" },
{ name: "Meek", subtitle: "(shy, mild, timid)" },
{ name: "Meek & Mild", subtitle: "(timid, docile, gentle)" },
{ name: "Melodramatic", subtitle: "(theatrical, sensational, showy)" },
{ name: "Mesmerizing", subtitle: "(fascinating, hypnotizing, charming)" },
{ name: "Messy", subtitle: "(sloppy, disorderly, unclean)" },
{ name: "Messy", subtitle: "(sloppy, dirty)" },
{ name: "Mischievous", subtitle: "(naughty, prankish, sly)" },
{ name: "Miserable", subtitle: "(wretched, pitiful, forlorn)" },
{ name: "Miserable", subtitle: "(unhappy, sorrowful)" },
{ name: "Misunderstood", subtitle: "(not grasped, not learned, not absorbed)" },
{ name: "Modern", subtitle: "(contemporary, fashionable, trendy)" },
{ name: "Mushy", subtitle: "(soft, squishy)" },
{ name: "Mysterious", subtitle: "(secretive, puzzling, strange)" },
{ name: "Mysterious", subtitle: "(strange, secretive)" },
{ name: "Mystical", subtitle: "(spiritual, secretive, esoteric)" },
{ name: "Naive", subtitle: "(unsophisticated, childlike, simple)" },
{ name: "Nasty", subtitle: "(mean, inclement, offensive)" },
{ name: "Nasty", subtitle: "(mean, wicked)" },
{ name: "Natural", subtitle: "(pure, simple, unadorned)" },
{ name: "Natural", subtitle: "(normal, pure)" },
{ name: "Naughty & Nice", subtitle: "(impish, mischievous, playful)" },
{ name: "Neat", subtitle: "(tidy, orderly, cool)" },
{ name: "Neat", subtitle: "(clean, orderly)" },
{ name: "Neat & Clean", subtitle: "(spotless, tidy, shipshape)" },
{ name: "Neglected", subtitle: "(ignored, disregarded, rejected)" },
{ name: "Nerdy", subtitle: "(unhip, uncool, dorky)" },
{ name: "New", subtitle: "(fresh, modern)" },
{ name: "New & Improved", subtitle: "(upgraded, enhanced, revised)" },
{ name: "Nice", subtitle: "(pleasant, kind)" },
{ name: "Noisy", subtitle: "(loud, not quiet)" },
{ name: "Normal", subtitle: "(usual, common, ordinary)" },
{ name: "Nutty", subtitle: "(kooky, foolish, nutlike)" },
{ name: "Obnoxious", subtitle: "(offensive, repulsive, annoying)" },
{ name: "Obscene", subtitle: "(offensive, indecent, lewd)" },
{ name: "Odd", subtitle: "(different, eccentric, bizarre)" },
{ name: "Odd", subtitle: "(unusual, strange)" },
{ name: "Offensive", subtitle: "(insulting, vulgar, attacking)" },
{ name: "Old", subtitle: "(aged, elderly, antiquated)" },
{ name: "Old", subtitle: "(not new, used)" },
{ name: "Old & Cranky", subtitle: "(crabby, cantankerous, aged)" },
{ name: "Old & Wise", subtitle: "(experienced, judicious, shrewd)" },
{ name: "On The Up & Up", subtitle: "(trustworthy, irreproachable, honest)" },
{ name: "Orderly", subtitle: "(methodical, formal, systematic)" },
{ name: "Ordinary", subtitle: "(usual, common, plain)" },
{ name: "Ordinary", subtitle: "(normal, common)" },
{ name: "Organic", subtitle: "(natural, clean, biological)" },
{ name: "Outrageous", subtitle: "(shocking, scandalous, disgraceful)" },
{ name: "Overwhelming", subtitle: "(exhaustive, breathtaking, monumental)" },
{ name: "Painful", subtitle: "(hurtful, agonizing, unbearable)" },
{ name: "Painful", subtitle: "(hurting, sore)" },
{ name: "Pale", subtitle: "(faded, colorless)" },
{ name: "Pathetic", subtitle: "(pitiful, distressing, heart-rending)" },
{ name: "Patriotic", subtitle: "(nationalistic, loyal, public-spirited)" },
{ name: "Peaceful", subtitle: "(serene, restful, calm)" },
{ name: "Peaceful", subtitle: "(calm, quiet)" },
{ name: "Perfect", subtitle: "(faultless, consummate, exact)" },
{ name: "Perfect", subtitle: "(ideal, wonderful)" },
{ name: "Perverse", subtitle: "(stubborn, obstinate, improper)" },
{ name: "Philosophical", subtitle: "(thoughtful, contemplative, wise)" },
{ name: "Phony", subtitle: "(false, artificial, imitation)" },
{ name: "Plain", subtitle: "(simple, evident, ordinary)" },
{ name: "Plain", subtitle: "(simple, dull)" },
{ name: "Plain & Simple", subtitle: "(unadorned, uncomplicated, clear)" },
{ name: "Playful", subtitle: "(fun, frisky, entertaining)" },
{ name: "Playful", subtitle: "(fun, cheerful)" },
{ name: "Pleasant", subtitle: "(enjoyable, nice)" },
{ name: "Plug & Play", subtitle: "(effortless, automatic, self-operating)" },
{ name: "Plump & Tender", subtitle: "(ripe, chubby, fleshy)" },
{ name: "Polite", subtitle: "(respectful, well-mannered)" },
{ name: "Poor", subtitle: "(not rich, unfortunate)" },
{ name: "Popular", subtitle: "(well-liked, accepted, preferred)" },
{ name: "Powerful", subtitle: "(strong, forceful, robust)" },
{ name: "Powerful", subtitle: "(strong, forceful)" },
{ name: "Practical", subtitle: "(useful, helpful)" },
{ name: "Pretty", subtitle: "(lovely, attractive, good-looking)" },
{ name: "Pretty", subtitle: "(good-looking, pleasing)" },
{ name: "Prim & Proper", subtitle: "(reserved, modest, prudish)" },
{ name: "Primitive", subtitle: "(prehistoric, primal, uncivilized)" },
{ name: "Principled", subtitle: "(conscientious, ethical, scrupulous)" },
{ name: "Profound", subtitle: "(deep, wise, thoughtful)" },
{ name: "Proud", subtitle: "(dignified, satisfied)" },
{ name: "Puffy", subtitle: "(swollen, billowy, bloated)" },
{ name: "Pure", subtitle: "(innocent, unadulterated, chaste)" },
{ name: "Quick", subtitle: "(fast, speedy)" },
{ name: "Quick & Dirty", subtitle: "(cheap, shoddy, inferior)" },
{ name: "Quiet", subtitle: "(peaceful, silent, calm)" },
{ name: "Quiet", subtitle: "(silent, noiseless)" },
{ name: "Radiant", subtitle: "(shining, glowing, sparkling)" },
{ name: "Radical", subtitle: "(unconventional, revolutionary, extreme)" },
{ name: "Rare", subtitle: "(scarce, unusual, half-cooked)" },
{ name: "Raw", subtitle: "(crude, uncooked, harsh)" },
{ name: "Realistic", subtitle: "(authentic, lifelike, reasonable)" },
{ name: "Refreshing", subtitle: "(brisk, invigorating, rejuvenating)" },
{ name: "Refined", subtitle: "(well-bred, purified, cultivated)" },
{ name: "Relaxed", subtitle: "(calm, not tense)" },
{ name: "Relaxing", subtitle: "(restful, calming, peaceful)" },
{ name: "Repulsive", subtitle: "(disgusting, offensive, foul)" },
{ name: "Respectable", subtitle: "(worthy, honorable, decent)" },
{ name: "Responsible", subtitle: "(accountable, obligated, mature)" },
{ name: "Revolutionary", subtitle: "(innovative, rebellious, radical)" },
{ name: "Rich", subtitle: "(wealthy, affluent, moneyed)" },
{ name: "Rich", subtitle: "(wealthy, not poor)" },
{ name: "Ridiculous", subtitle: "(preposterous, absurd, ludicrous)" },
{ name: "Risky", subtitle: "(hazardous, daring, speculative)" },
{ name: "Rough", subtitle: "(scratchy, uneven, jagged)" },
{ name: "Rough", subtitle: "(not smooth, not gentle)" },
{ name: "Rough & Ready", subtitle: "(crude, makeshift, prepared)" },
{ name: "Round", subtitle: "(circular, ring shaped)" },
{ name: "Sad", subtitle: "(unhappy, gloomy)" },
{ name: "Saintly", subtitle: "(virtuous, angelic, divine)" },
{ name: "Sappy", subtitle: "(gooey, mushy, romantic)" },
{ name: "Scary", subtitle: "(frightening, absurd, ugly)" },
{ name: "Scary", subtitle: "(frightening, spooky)" },
{ name: "Scenic", subtitle: "(picturesque, dramatic, panoramic)" },
{ name: "Scented", subtitle: "(perfumed, fragrant)" },
{ name: "Secretive", subtitle: "(concealed, covert, veiled)" },
{ name: "Selfish", subtitle: "(stingy, greedy, miserly)" },
{ name: "Sensational", subtitle: "(thrilling, startling, melodramatic)" },
{ name: "Senseless", subtitle: "(meaningless, absurd, foolish)" },
{ name: "Sensitive", subtitle: "(susceptible, sympathetic, tender)" },
{ name: "Sensual", subtitle: "(tactile, pleasing, sexual)" },
{ name: "Serious", subtitle: "(important, thoughtful)" },
{ name: "Sexy", subtitle: "(arousing, appealing, seductive)" },
{ name: "Shaggy", subtitle: "(bushy, stringy)" },
{ name: "Shallow", subtitle: "(superficial, trivial, not deep)" },
{ name: "Sharp", subtitle: "(pointed, keen, acute)" },
{ name: "Sharp", subtitle: "(pointed, not rounded)" },
{ name: "Shiny", subtitle: "(reflective, gleaming, polished)" },
{ name: "Shiny", subtitle: "(bright, glossy)" },
{ name: "Shocking", subtitle: "(frightening, electrifying, startling)" },
{ name: "Short", subtitle: "(not long, not tall)" },
{ name: "Short & Stout", subtitle: "(plump, portly, tubby)" },
{ name: "Short & Sweet", subtitle: "(precise, clear-cut, succinct)" },
{ name: "Shy", subtitle: "(bashful, timid, cautious)" },
{ name: "Shy", subtitle: "(bashful, timid)" },
{ name: "Sick & Tired", subtitle: "(worn out, exhausted, exasperated)" },
{ name: "Sick & Twisted", subtitle: "(depraved, wicked, lascivious)" },
{ name: "Sickening", subtitle: "(nauseating, disgusting, revolting)" },
{ name: "Sickening", subtitle: "(disgusting, horrible)" },
{ name: "Silent", subtitle: "(quiet, still)" },
{ name: "Silky", subtitle: "(smooth, soft)" },
{ name: "Silly", subtitle: "(goofy, absurd, nonsensical)" },
{ name: "Silly", subtitle: "(foolish, goofy)" },
{ name: "Simple", subtitle: "(plain, easy)" },
{ name: "Skillful", subtitle: "(expert, talented)" },
{ name: "Skinny", subtitle: "(thin, lean)" },
{ name: "Slender", subtitle: "(slim, small)" },
{ name: "Slimy", subtitle: "(slippery, gooey)" },
{ name: "Slippery", subtitle: "(slick, sliding)" },
{ name: "Sloppy", subtitle: "(messy, careless)" },
{ name: "Slow", subtitle: "(not fast, pokey)" },
{ name: "Slow & Steady", subtitle: "(reliable, deliberate, ponderous)" },
{ name: "Sluggish", subtitle: "(inactive, lazy, slothful)" },
{ name: "Small", subtitle: "(little, not large)" },
{ name: "Smart", subtitle: "(intelligent, stylish, witty)" },
{ name: "Smart", subtitle: "(intelligent, clever)" },
{ name: "Smelly", subtitle: "(stinky, odorous, rank)" },
{ name: "Smelly", subtitle: "(stinky, bad odor)" },
{ name: "Smooth", subtitle: "(even, level, flat)" },
{ name: "Smooth", subtitle: "(not bumpy, flat)" },
{ name: "Smooth & Creamy", subtitle: "(silky, velvety, rich)" },
{ name: "Snappy", subtitle: "(stylish, trendy, fast)" },
{ name: "Sneaky", subtitle: "(tricky, mean)" },
{ name: "Soft", subtitle: "(malleable, pliable, mushy)" },
{ name: "Soft", subtitle: "(not hard, tender)" },
{ name: "Sophisticated", subtitle: "(urbane, cosmopolitan, complex)" },
{ name: "Sour", subtitle: "(bitter, tart)" },
{ name: "Special", subtitle: "(distinctive, unique, original)" },
{ name: "Special", subtitle: "(individual, unique)" },
{ name: "Speedy", subtitle: "(quick, rapid, fast)" },
{ name: "Speedy", subtitle: "(quick, fast)" },
{ name: "Spic & Span", subtitle: "(spotless, tidy, clean)" },
{ name: "Spicy", subtitle: "(flavorable, tangy, hot)" },
{ name: "Spiritual", subtitle: "(religious, inspired, supernatural)" },
{ name: "Spooky", subtitle: "(scary, weird, ghostly)" },
{ name: "Spooky", subtitle: "(scary, frightening)" },
{ name: "Sporty", subtitle: "(athletic, active)" },
{ name: "Spotless", subtitle: "(clean, pure)" },
{ name: "Spunky", subtitle: "(perky, lively, spirited)" },
{ name: "Square", subtitle: "(rectangular, uncool, dull)" },
{ name: "Squeaky Clean", subtitle: "(pure, immaculate, unapproachable)" },
{ name: "Stereotyped", subtitle: "(pigeonholed, caricatured, characterized)" },
{ name: "Sticky", subtitle: "(gummy, pasty)" },
{ name: "Stinky", subtitle: "(smelly, bad odor)" },
{ name: "Straight", subtitle: "(not curved, direct)" },
{ name: "Strange", subtitle: "(odd, unusual)" },
{ name: "Strong", subtitle: "(powerful, forceful)" },
{ name: "Stunning", subtitle: "(astonishing, staggering, astounding)" },
{ name: "Stupid", subtitle: "(ignorant, unintelligent, inane)" },
{ name: "Sultry", subtitle: "(sweltering, humid, sensual)" },
{ name: "Surprising", subtitle: "(unexpected, amazing)" },
{ name: "Sweet", subtitle: "(sugary, caring, good)" },
{ name: "Sweet", subtitle: "(sugary, nice)" },
{ name: "Swift", subtitle: "(quick, speedy, expeditious)" },
{ name: "Swift & Sure", subtitle: "(steady, prompt, definite)" },
{ name: "Talented", subtitle: "(gifted, clever, skillful)" },
{ name: "Talented", subtitle: "(skillful, gifted)" },
{ name: "Tall", subtitle: "(not short, not low)" },
{ name: "Tame", subtitle: "(subdued, gentle, trained)" },
{ name: "Tame", subtitle: "(not wild, mild)" },
{ name: "Tasty", subtitle: "(flavorful, savory, appetizing)" },
{ name: "Tasty", subtitle: "(flavorful, yummy)" },
{ name: "Technological", subtitle: "(scientific, futuristic, mechanical)" },
{ name: "Temperamental", subtitle: "(moody, irritable, short-tempered)" },
{ name: "Tempting", subtitle: "(seductive, enticing, alluring)" },
{ name: "Tender", subtitle: "(soft, compassionate, fragile)" },
{ name: "Terrible", subtitle: "(awful, dreadful)" },
{ name: "Terrific", subtitle: "(sensational, fabulous, severe)" },
{ name: "Thick", subtitle: "(wide, solid)" },
{ name: "Thick & Chunky", subtitle: "(bulky, heavy, lumpy)" },
{ name: "Thin", subtitle: "(skinny, narrow)" },
{ name: "Thoughtful", subtitle: "(caring, unselfish)" },
{ name: "Timeless", subtitle: "(classic, ageless, well-established)" },
{ name: "Tiny", subtitle: "(little, very small)" },
{ name: "Tormenting", subtitle: "(torturing, harassing, agonizing)" },
{ name: "Torn & Tattered", subtitle: "(shabby, ragged, grungy)" },
{ name: "Touch & Go", subtitle: "(indecisive, uncertain, insecure)" },
{ name: "Touchy-Feely", subtitle: "(affectionate, tactile, huggy)" },
{ name: "Tough", subtitle: "(strong, firm, difficult)" },
{ name: "Tough", subtitle: "(strong, hard)" },
{ name: "Trashy", subtitle: "(shameless, nasty, indecent)" },
{ name: "Tried & True", subtitle: "(tested, proven, trustworthy)" },
{ name: "True & Blue", subtitle: "(loyal, faithful, patriotic)" },
{ name: "Trustworthy", subtitle: "(honest, reliable, unfailing)" },
{ name: "Trustworthy", subtitle: "(dependable, honest)" },
{ name: "Twisted", subtitle: "(distorted, warped, perverted)" },
{ name: "Ugly", subtitle: "(not pretty, unpleasant)" },
{ name: "Unbelievable", subtitle: "(incredible, far-fetched, impossible)" },
{ name: "Unforgettable", subtitle: "(notable, impressive, remarkable)" },
{ name: "Unforgettable", subtitle: "(memorable, treasured)" },
{ name: "Unhappy", subtitle: "(sad, sorrowful)" },
{ name: "Unhealthy", subtitle: "(risky, sickly, dangerous)" },
{ name: "Unnatural", subtitle: "(abnormal, artificial, bizarre)" },
{ name: "Unreal", subtitle: "(imaginary, illusionary, unbelievable)" },
{ name: "Unscrupulous", subtitle: "(unethical, corrupt, unprincipled)" },
{ name: "Unusual", subtitle: "(rare, odd, uncommon)" },
{ name: "Untamed", subtitle: "(wild, natural)" },
{ name: "Up & Coming", subtitle: "(promising, enterprising, gifted)" },
{ name: "Up & Down", subtitle: "(volatile, variable, vertical)" },
{ name: "Useful", subtitle: "(helpful, handy)" },
{ name: "Useless", subtitle: "(worthless, ineffective, unneeded)" },
{ name: "Useless", subtitle: "(worthless, not valuable)" },
{ name: "Vain", subtitle: "(conceited, arrogant, fruitless)" },
{ name: "Valuable", subtitle: "(expensive, important)" },
{ name: "Violent", subtitle: "(furious, vicious, destructive)" },
{ name: "Virtuous", subtitle: "(worthy, righteous, chaste)" },
{ name: "Visionary", subtitle: "(idealistic, prophetic, far-seeing)" },
{ name: "Warm", subtitle: "(tepid, mild, affectionate)" },
{ name: "Warm", subtitle: "(heated, somewhat hot)" },
{ name: "Warm & Cozy", subtitle: "(snug, comfy, friendly)" },
{ name: "Warm & Fuzzy", subtitle: "(kindhearted, loving, affectionate)" },
{ name: "Wash & Wear", subtitle: "(durable, easy-care, sturdy)" },
{ name: "Weak", subtitle: "(not strong, sickly)" },
{ name: "Weird", subtitle: "(abnormal, peculiar, odd)" },
{ name: "Weird", subtitle: "(odd, mysterious)" },
{ name: "Wet", subtitle: "(watery, soaked)" },
{ name: "Whimsical", subtitle: "(humourous, peculiar, fanciful)" },
{ name: "Wicked", subtitle: "(evil, corrupt, depraved)" },
{ name: "Wide", subtitle: "(broad, thick)" },
{ name: "Wild", subtitle: "(untamed, savage, ferocious)" },
{ name: "Wild", subtitle: "(not tame, crazy)" },
{ name: "Wild & Wooly", subtitle: "(untamed, uncontrolled, reckless)" },
{ name: "Wired", subtitle: "(strained, tense, nervous)" },
{ name: "Witty", subtitle: "(clever, humorous, cunning)" },
{ name: "Woebegone", subtitle: "(dismal, sorrowful, bummed out)" },
{ name: "Wonderful", subtitle: "(great, excellent)" },
{ name: "Worldly", subtitle: "(experienced, sophisticated, materialistic)" },
{ name: "Worthless", subtitle: "(useless, meaningless)" },
{ name: "Young", subtitle: "(not old, new)" },
{ name: "Young & Restless", subtitle: "(fidgety, impatient, flighty)" },
{ name: "Yucky", subtitle: "(icky, sickening)" },
{ name: "Zany", subtitle: "(crazy, funny, wacky)" },
];

export { blackcards };
