const blackcards =
[
  "I may not be much to look at, but I fuck like __________.",
  "Errbody in the club __________.",
  "Son, take it from someone who's been around the block a few times. Nothin' puts her in the mood like __________.",
  "Art isn't just a painting in a stuffy museum. Art is alive. Art is __________.",
  "You won't believe what's in my pussy. It's __________.",
  "What's the most problematic?",
  "Feeling so grateful! #amazing #mylife #__________",
  "What's the gayest?",
  "Girls just wanna have __________.",
  "One more thing. Watch out for Big Mike. They say he killed a man with __________.",
  "Well, shit. My eyes ain't so good, but I'll eat my own boot if that ain't __________!",
  "If at first you don't succeed, try __________.",
  "What will end racism once and for all?",
  "I'll take the BBQ bacon burger with a fried egg and fuck it how about __________.",
  "Well if __________ is a crime, then lock me up!",
  "We do not shake with our left hands in this country. That is the hand we use for __________.",
  "You know who else liked __________? Hitler.",
  "Poor Brandon, still living in his parents' basement. I hear he never got over __________.",
  "What totally destroyed my asshole?",
  "I don't believe in God. I believe in __________.",
  "___________: Brought to you by __________.",
  "Then the princess kissed the frog, and all of a sudden the frog was __________!",
  "I've got rhythm, I've got music, I've got __________. Who could ask for anything more?",
  "No, no, no, no, no, NO! I will NOT let __________ ruin this wedding.",
  "Coming to Red Lobster this month, __________.",
  "Ooo, daddy like __________.",
  "Best you go back where you came from, now. We don't take too kindly to __________ in these parts.",
  "Summer lovin', had me a blast. __________, happened so fast.",
  "LSD + __________ = really bad time.",
  "What are all those whales singing about?",
  "As Teddy Roosevelt said, the four manly virtues are honor, temperance, industry, and __________. ",
  "I tell you, it was a non-stop fuckfest. When it was over, my asshole looked like __________.",
  "What turned me into a Republican?",
  "I'm sorry, sir, but your insurance plan doesn't cover injuries caused by __________.",
  "Run, run, as fast as you can! You can't catch me, I'm __________!",
  "There is no God. It's just __________ and then you die.",
  "She's just one of the guys, you know? She likes beer, and football, and __________.",
  "This Friday at the Liquid Lounge, it's __________ Night! Ladies drink free.",
  "What sucks balls?",
  "I've had a horrible vision, father. I saw mountains crumbling, stars falling from the sky. I saw __________.",
  "Oh no! Siri, how do I fix __________?",
  "Dance like there's nobody watching, love like you'll never be hurt, and live like you're __________.",
  "Why am I laughing and crying and taking off my clothes?",
  "She's a lady in the streets, __________ in the sheets.",
  "What's about to take this dance floor to the next level?",
  "CNN breaking news! Scientists discover __________.",
  "Most Americans would not vote for a candidate who is openly __________.",
  "Congratulations! You have been selected for our summer internship program. While we are unable to offer a salary, we can offer you __________.",
  "In the 1950s, psychologists prescribed __________ as a cure for homosexuality.",
  "As reparations for slavery, all African Americans will receive __________.",
  "With a one-time gift of just $10, you can save this child from __________.",
  "Google Calendar alert: __________ in 10 minutes.",
  "Hey Reddit! I'm __________. Ask me anything.",
  "Introducing X-treme Baseball! It's like baseball, but with __________!",
  "What is Batman's guilty pleasure?",
  "TSA guidelines now prohibit __________ on airplanes.",
  "Next from J.K. Rowling: Harry Potter and the Chamber of __________.",
  "I'm sorry, Professor, but I couldn't complete my homework because of __________.",
  "Dude, do not go in that bathroom. There's __________ in there.",
  "How did I lose my virginity?",
  "It's a pity that kids these days are all getting involved with __________.",
  "__________. Betcha can't have just one!",
  "Kids, I don't need drugs to get high. I'm high on __________.",
  "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________.",
  "In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time.",
  "What's my secret power?",
  "I'm going on a cleanse this week. Nothing but kale juice and __________.",
  "When Pharaoh remained unmoved, Moses called down a Plague of __________.",
  "Just once, I'd like to hear you say 'Thanks, Mom. Thanks for __________.'",
  "Daddy, why is mommy crying?",
  "50% of all marriages end in __________.",
  "My fellow Americans: Before this decade is out, we will have __________ on the moon!",
  "This season at Steppenwolf, Samuel Beckett's classic existential play: Waiting for __________.",
  "Instead of coal, Santa now gives the bad children __________.",
  "Life for American Indians was forever changed when the White Man introduced them to __________.",
  "What's Teach For America using to inspire inner city students to succeed?",
  "Maybe she's born with it. Maybe it's __________.",
  "What is George W. Bush thinking about right now?",
  "White people like __________.",
  "Why do I hurt all over?",
  "A romantic, candlelit dinner would be incomplete without __________.",
  "Just saw this upsetting video! Please retweet!! #stop__________",
  "Fun tip! When your man asks you to go down on him, try surprising him with __________ instead.",
  "The class field trip was completely ruined by __________.",
  "What's a girl's best friend?",
  "Dear Abby, I'm having some trouble with __________ and would like your advice.",
  "When I am President, I will create the Department of __________.",
  "What are my parents hiding from me?",
  "What never fails to liven up the party?",
  "IF you like __________, YOU MIGHT BE A REDNECK.",
  "What made my first kiss so awkward?",
  "Hey guys, welcome to Chili's! Would you like to start the night off right with __________?",
  "I got 99 problems but __________ ain't one.",
  "__________. It's a trap!",
  "Bravo's new reality show features eight washed-up celebrities living with __________.",
  "What would grandma find disturbing, yet oddly charming?",
  "__________. That was so metal.",
  "During sex, I like to think about __________.",
  "What ended my last relationship?",
  "What's that sound?",
  "Uh, hey guys, I know this was my idea, but I'm having serious doubts about __________.",
  "Why am I sticky?",
  "I'm no doctor but I'm pretty sure what you're suffering from is called '__________.'",
  "What's there a ton of in heaven?",
  "After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: __________.",
  "What will always get you laid?",
  "__________: kid-tested, mother-approved.",
  "Why can't I sleep at night?",
  "What's that smell?",
  "After eight years in the White House, how is Obama finally letting loose?",
  "Coming to Broadway this season, __________: The Musical.",
  "But before I kill you, Mr. Bond, I must show you __________.",
  "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to __________.",
  "Next on ESPNThe World Series of __________.",
  "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________.",
  "Military historians remember Alexander the Great for his brilliant use of __________ against the Persians.",
  "War! What is it good for?",
  "What gives me uncontrollable gas?",
  "The Chevy Tahoe. With the power and space to take __________ everywhere you go.",
  "Well if you'll excuse me, gentlemen, I have a date with __________.",
  "Alternative medicine is now embracing the curative powers of __________.",
  "As the mom of five rambunctious boys, I'm no stranger to __________.",
  "__________. High five, bro.",
  "Today on Maury: 'Help! My son is __________!'",
  "I get by with a little help from __________.",
  "âœ®âœ©âœ©âœ©âœ© Do NOT go here! Found __________ in my Kung Pao chicken!",
  "I drink to forget __________.",
  "I'm LeBron James, and when I'm not slamming dunks, I love __________.",
  "What makes life worth living?",
  "Arby's: We Have __________.",
  "Mr. and Mrs. Diaz, we called you in because we're concerned about Cynthia. Are you aware that your daughter is __________?",
  "If you can't be with the one you love, love __________.",
  "Brought to you by Bud Light, the Official Beer of __________.",
  "Click here for __________!!!",
  "Check me out, yo! I call this dance move '__________.'",
  "Old Macdonald had __________. E-I-E-I-O.",
  "Men's Wearhouse. You're gonna like __________. I guarantee it.",
  "Oh you haaaaaaave to see this new documentary on Netflix. I don't want to give anything away, but let's just say it will change the way you look at __________.",
  "It's finally happening! I'm finally doing it! Yes! It's time for __________!",
  "Oh no! Here it comes! Ohhh god! It's __________!",
  "Unfortunately, no one can be told what __________ is. You have to experience it for yourself.",
  "What is secretly a Russian plot to destabilize the West? ",
  "That's bullshit! They can't fire me for __________!",
  "Well the weather outside is frightful, but __________ is so delightful.",
  "Rub a dub dub, __________ in a tub!",
  "I swear to God I'm gonna murder my husband if he doesn't shut the fuck up about __________.",
  "You can call me David Copperfield, because I'm about to make __________ disappear.",
  "If only there were 26 hours in a day, I'd have time for __________.",
  "For hunting in the King's forest, I sentence you to death by __________.",
  "Hey honey...for the bedroom, were you thinking 'Robin's egg blue' or '__________ Pink'?",
  "New at TGI Fridays! It's what you've been waiting for: The __________ Burger.",
  "Some heroes fight for justice, others for honor. I fight for __________.",
  "5, 4, 3, 2, 1, __________!",
  "One, two, three and to the four, Snoop Doggy Dogg and Dr. Dre is __________.",
  "Personal foul: __________. 15 yard penalty. Automatic first down.",
  "Yeah that's so hot. I'm so close. Talk about __________ again. OH I'M CUMMING!",
  "__________? Fuggedaboutit!",
  "Here's a little something I learned in business school: The customer is always __________.",
  "__________. Changes. Everything.",
  "Oh my god Cindy! What happened to your face?!",
  "I feel the need, the need for __________!",
  "In Radiohead's new single, Thom Yorke repeats the phrase '__________' dozens of times over a skittering drumbeat.",
  "I hate this job. I hate this place. Most of all I hate __________. I quit.",
  "What has my life become? I'm sitting here jerking off to a video called 'coed absolutely destroyed by __________.'",
  "Bailamos! Let __________ take you over. Bailamos!",
  "I just love __________, but it makes me barf every time. ",
  "What is the essence of capitalism?",
  "Goldfinger: He's the man, the man with __________.",
  "What sounds great after four appletinis?",
  "The internet is hungry. It wants __________.",
  "Say it loud! I'm __________ and I'm proud!",
  "It's 2018. As a woman, I shouldn't have to apologize for __________.",
  "You and your sister excel in different ways. She's got her violin and you've got __________.",
  "Why did the chicken cross the road?",
  "Principal Wheeler, please excuse my idiot son for __________. Heâ€™s an idiot.",
  "Seriously guys, there's nothing funny about __________.",
  "America is hungry. America wants __________.",
  "BILL COSBY __________ !!!!!!!!!!",
  "Duuude. You have got to go to space. __________ is awesome in space.",
  "Hey guys, I finally found out why I was pissing blood for three weeks! It was __________!",
  "In the future, when robots have taken all the jobs, we will devote our energy to __________.",
  "You. Me. My private yacht. __________.",
  "Give me 10 good men and 48 hours. I'll get you __________.",
  "Why my mustache smell so bad?",
  "Millions of copies sold! Donald Trump's 'The Art of __________.'",
  "What's hot, smelly, and about to die?",
  "Knock knock. Who's there? __________.",
  "Life isn't just about getting laid, Gary. There's also __________.",
  "This place rules. It's basically the Disneyland of __________.",
  "Times have changed. If you want to meet people in New York, you gotta be down for __________.",
  "What's up YouTube? User DanTheMan wanted to see __________, so here we go. ",
  "In this Great Courses audio series, we'll explore life's big questions. Who are we? What is our purpose? What is the meaning of __________?",
  "It's late at night and you're in bed with your lover, Patrick Stewart. He leans over and asks 'How about __________?'",
  "I Survived __________ And All I Got Was This Lousy T-Shirt.",
  "Coming up on TLC: __________ Wars.",
  "Oh my god guys, can we calm down about __________ for 5 fucking seconds?",
  "True love is __________.",
  "I have solved politics. My solution is __________.",
  "Sorry for staring, mister. It's just that I ain't never seen __________ before.",
  "Ain't it nifty?! Barb and Bob hit 50, so get off your ass and raise a glass to 50 years of __________.",
];

export { blackcards };
